# Generated by Django 6.0 on 2025-12-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_URL',
            field=models.URLField(blank=True),
        ),
    ]
